openapi: "3.0.2"
info:
  title: API Roles
  version: "1.0"
tags:
  - name: Roles
    description: Role specific data.
paths:
  /roles:
    get:
      summary: List all roles
      operationId: listRoles
      tags:
        - roles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Role'
    post:
      summary: Create a role
      operationId: createRoles
      tags:
        - roles
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Role'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Role'
  /roles/{roleId}:
    get:
      summary: Get role by id
      operationId: getRole
      parameters:
        - name: roleId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Role'
        '404':
          description: NOT FOUND
components:
  schemas:
    Role:
      type: object
      required:
        - roleId
        - name
      properties:
        roleId:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string